from __future__ import annotations

import json
from dataclasses import dataclass, field
from typing import Any

from core.agents.registry import AgentRegistry
from core.llm.base import BaseLLM


SUPERVISOR_PROMPT = """
You are a supervisor agent.

Your task is to:
- analyze the user request
- delegate tasks to low-level agents
- evaluate execution results
- continue execution if needed
- produce the final answer

You must respond ONLY in JSON.

Available response formats:

1. Delegate tasks:
{
    "type": "tasks",
    "tasks": [
        {
            "agent": "researcher",
            "task": "Find information about ..."
        }
    ]
}

2. Return final answer:
{
    "type": "final",
    "answer": "Final response to the user"
}
"""


@dataclass(slots=True)
class Task:
    """Task generated by the supervisor."""

    agent: str
    task: str


@dataclass(slots=True)
class AgentResult:
    """Result returned by a low-level agent."""

    agent: str
    task: str
    success: bool
    result: str


@dataclass(slots=True)
class ExecutionContext:
    """Stores orchestration execution state."""

    user_input: str
    agent_results: list[AgentResult] = field(default_factory=list)


class Orchestrator:
    """Supervisor agent coordinating low-level agents."""

    def __init__(
        self,
        llm: BaseLLM,
        registry: AgentRegistry,
        max_iterations: int = 5,
    ) -> None:
        self.llm = llm
        self.registry = registry
        self.max_iterations = max_iterations

    async def run(self, user_input: str) -> str:
        """Execute supervisor orchestration loop."""

        context = ExecutionContext(user_input=user_input)

        for _ in range(self.max_iterations):
            messages = self._build_messages(context)

            response = await self.llm.call(messages=messages)

            parsed_response = self._parse_response(response)

            response_type = parsed_response.get("type")

            if response_type == "final":
                return parsed_response["answer"]

            if response_type == "tasks":
                tasks = self._parse_tasks(parsed_response)

                await self._execute_tasks(tasks, context)

                continue

            raise ValueError("Unknown supervisor response type")

        return "Unable to complete the task"

    def _build_messages(
        self,
        context: ExecutionContext,
    ) -> list[dict[str, str]]:
        """Build LLM messages from execution context."""

        messages: list[dict[str, str]] = [
            {
                "role": "system",
                "content": SUPERVISOR_PROMPT,
            },
            {
                "role": "user",
                "content": context.user_input,
            },
        ]

        if context.agent_results:
            results_summary = self._build_results_summary(
                context.agent_results
            )

            messages.append(
                {
                    "role": "system",
                    "content": results_summary,
                }
            )

        return messages

    def _build_results_summary(
        self,
        results: list[AgentResult],
    ) -> str:
        """Convert agent results into structured text summary."""

        summary_parts = ["Completed agent tasks:"]

        for result in results:
            summary_parts.append(
                (
                    f"\nAgent: {result.agent}\n"
                    f"Task: {result.task}\n"
                    f"Success: {result.success}\n"
                    f"Result: {result.result}\n"
                )
            )

        return "\n".join(summary_parts)

    def _parse_response(self, response: Any) -> dict[str, Any]:
        """Parse supervisor JSON response."""

        if isinstance(response, dict):
            return response

        if isinstance(response, str):
            try:
                return json.loads(response)
            except json.JSONDecodeError as error:
                raise ValueError(
                    "Supervisor returned invalid JSON"
                ) from error

        raise ValueError("Unsupported LLM response format")

    def _parse_tasks(
        self,
        response: dict[str, Any],
    ) -> list[Task]:
        """Convert JSON task list into Task objects."""

        tasks: list[Task] = []

        for item in response.get("tasks", []):
            tasks.append(
                Task(
                    agent=item["agent"],
                    task=item["task"],
                )
            )

        return tasks

    async def _execute_tasks(
        self,
        tasks: list[Task],
        context: ExecutionContext,
    ) -> None:
        """Execute low-level agent tasks."""

        for task in tasks:
            agent = self.registry.get(task.agent)

            try:
                result = await agent.run(task.task)

                context.agent_results.append(
                    AgentResult(
                        agent=task.agent,
                        task=task.task,
                        success=True,
                        result=str(result),
                    )
                )

            except Exception as error:
                context.agent_results.append(
                    AgentResult(
                        agent=task.agent,
                        task=task.task,
                        success=False,
                        result=str(error),
                    )
                )
