from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from enum import Enum
from typing import Any


class AgentCapability(str, Enum):
    """Supported agent capabilities.

    Capabilities help the supervisor understand
    what each low-level agent can do.
    """

    SEARCH = "search"
    REMINDER = "reminder"
    CODING = "coding"
    PLANNING = "planning"
    FILES = "files"
    WEB = "web"
    ANALYSIS = "analysis"


@dataclass(slots=True)
class AgentMetadata:
    """Describes a low-level agent.

    Attributes:
        name:
            Unique agent identifier.

        description:
            Human-readable explanation of agent purpose.

        capabilities:
            Functional areas supported by the agent.

        version:
            Agent implementation version.

        tags:
            Optional labels for filtering/grouping.
    """

    name: str
    description: str
    capabilities: set[AgentCapability] = field(default_factory=set)
    version: str = "1.0"
    tags: set[str] = field(default_factory=set)


class BaseAgent(ABC):
    """Base interface for all low-level agents."""

    metadata: AgentMetadata

    @abstractmethod
    async def run(
        self,
        task: str,
        context: dict[str, Any] | None = None,
    ) -> Any:
        """Execute a task.

        Args:
            task:
                Task description generated by supervisor.

            context:
                Optional execution context.

        Returns:
            Agent execution result.
        """


class AgentRegistry:
    """Stores and manages registered agents.

    The registry is used by the supervisor to:
    - discover available agents
    - access agents by name
    - filter agents by capability
    """

    def __init__(self) -> None:
        self._agents: dict[str, BaseAgent] = {}

    def register(self, agent: BaseAgent) -> None:
        """Register a new agent.

        Raises:
            ValueError:
                If an agent with the same name already exists.
        """

        agent_name = agent.metadata.name

        if agent_name in self._agents:
            raise ValueError(
                f"Agent '{agent_name}' is already registered"
            )

        self._agents[agent_name] = agent

    def get(self, agent_name: str) -> BaseAgent:
        """Return agent by name.

        Raises:
            ValueError:
                If agent is not registered.
        """

        if agent_name not in self._agents:
            raise ValueError(
                f"Agent '{agent_name}' is not registered"
            )

        return self._agents[agent_name]

    def exists(self, agent_name: str) -> bool:
        """Check whether agent exists in registry."""

        return agent_name in self._agents

    def list_agents(self) -> list[AgentMetadata]:
        """Return metadata for all registered agents."""

        return [
            agent.metadata
            for agent in self._agents.values()
        ]

    def find_by_capability(
        self,
        capability: AgentCapability,
    ) -> list[BaseAgent]:
        """Return agents supporting a capability."""

        return [
            agent
            for agent in self._agents.values()
            if capability in agent.metadata.capabilities
        ]


# Global registry instance.
#
# Can be imported and populated during application startup.
registry = AgentRegistry()
